language: node_js
services:
  - xvfb
  - docker
node_js:
  - lts/dubnium
os:
  - linux
env:
  - NODE_ENV=test
  - NODE_ENV=staging
  - NODE_ENV=production
cache:
  directories:
    - 'node_modules'
before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > $tmpdaemon
  - sudo mv $tmpdaemon /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo service docker restart
  - chmod ugo+x ./test/scripts/setup_test_environment.sh
  - sudo ./test/scripts/setup_test_environment.sh
  - docker system info
install:
  - npm --production=false install
script:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ] && [ "${NODE_ENV}" = "test" ]; then npm run mock-server:build; fi
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then audit-ci --moderate; fi
  - npm run build
  - chmod ugo+x ./test.sh
  - ./test.sh
after_success:
  - python node_modules/travis-weigh-in/weigh_in.py dist/onfido.min.js
  - chmod ugo+x ./deploy.sh
  - ./deploy.sh
